{% set name = "mesa-viz-tornado" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Mesa-Viz-Tornado-{{ version }}.tar.gz
  sha256: adee8361310aefaf23d23d379e94113c6969b69e35054dcd035b6e0d82561788

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - tornado

test:
  imports:
    - mesa_viz_tornado
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/projectmesa/mesa-viz-tornado
  summary: Tornado-based visualization framework for Mesa
  description: 
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - adamamer20
